### ISSUE TITLE
Refactor SegmentedSwitch to include title

### ISSUE THREAD

**Issue by derekstavis** [pagarme/former-kit#108]
### Context

Currently, `SegmentedSwitch` component allow to pass an array of strings `items` and a string `selected` option. The `items` strings are used as titles for the options, which could be strange in situations where your state model differs the title you'd like to display.

### Description

The proposition is to refactor the component's interface to allow better semantics:

```jsx
<SegmentedSwitch
  options={[
    {
      title: 'Portuguese',
      value: 'pt-BR',
    },
    {
      title: 'English',
      value: 'en-US',
    },
  ]}
/>
```

### Requirements

- [x] Refactor component interface
- [x] Refactor tests to new interface
- [x] Refactor storybook usages

**Comment by lucasjs** [comment]
https://github.com/pagarme/former-kit/pull/109
