### ISSUE TITLE
Steps should accept 'pending'

### ISSUE THREAD

**Issue by LeoNero** [pagarme/former-kit#111]
### Context

The `Steps` component only accepts `current` and `success`. However, not all steps fit in those cases. For example, if I have 4 steps to complete and I am in the third step, the fourth step is 'pending'

**Comment by uselessdev** [comment]
I think `pending` status are useless, because all next steps are 'pending'

**Comment by LeoNero** [comment]
I disagree, because we must pass the `status` of the step to the component. If the component accepts only `current|error`, what would we pass to `status`?
