### ISSUE TITLE
Add prop overflow in Card component

### ISSUE THREAD

**Issue by Deivis** [pagarme/former-kit#150]
### Context
The `Card` component don't allow the overflow usage, this creates bugs like the following:
![screenshot from 2018-06-25 20-28-21](https://user-images.githubusercontent.com/1773766/41880795-68007e78-78b6-11e8-8881-031512d4b0dc.png)

### Requirements
- [ ] Allow overflow usage in `Card` component

**Comment by uselessdev** [comment]
I think we could solve this by removing the overflow prop https://github.com/pagarme/former-kit-skin-pagarme/blob/master/src/styles/card/index.css#L14

**Comment by lucasjs** [comment]
I haven't found any card with a bug because of the `overflow: initial`, so I agree with @uselessdev.
