### ISSUE TITLE
Criar componente SnackBar

### ISSUE THREAD

**Issue by Deivis** [pagarme/former-kit#167]
### Context
Criar um componente de SnackBar com uma interface semelhante ao `Alert` já estabelecido no former-kit. Ele será usado para enviar notificações rápidas ao usuário às quais podem vir a sumir depois de um tempo.

### Example
![screenshot from 2018-07-12 15-55-04](https://user-images.githubusercontent.com/1773766/42653487-fbe7c5fa-85eb-11e8-91c3-147e0dd63b22.png)
https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/5a01eeace859f8751b16b22b

### Description
Deve seguir o padrão de nomenclatura da interface do `alert` ( https://github.com/pagarme/former-kit/tree/master/src/Alert ) do `former-kit`, e também o padrão de cores definidas de acordo com a propriedade `type` recebida, que pode ser um dos seguintes valores: `error, info, success, warning`

```
<SnackBar
  action="texto"
  dismissTimeout={1000}
  icon={<Icon />}
  onDismiss={ event => event }
  theme={}
  type="error"
  
>
  <span>children content</span>
</SnackBar>
```

### Requirements
- [x] Manter posicionamento absoluto em referência ao corpo (Main) da aplicação
- [x] A cor tem que estar de acordo com o `type` recebida
- [x] Quando recebida a propriedade `dismissTimeout` ela vai disparar um `setTimeout` que quando chegar ao fim deve chamar a função `onDismiss`
- [x] Quando disparar a função `onDismiss` ela vai também disparar uma animação para remover o componente da tela debaixo para cima.
- [x] A entrada do componete na tela deve ser feita com uma animação de `Fade` do `Transition`. E a saída (close) deve ser através do mesmo tipo de animação.
- [x] Ao clicar no ícone de fechar deve ser disparada a função `onDismiss`

**Comment by macabeus** [comment]
@Deivis I think that we could close this issue
