### ISSUE TITLE
Add Truncate component

### ISSUE THREAD

**Issue by uselessdev** [pagarme/former-kit#176]
### Context
Currently if a text exceeds the size of the column in the table, the text is show exceeding the parent element, so we need to add a component to handle with this and truncate the text.

### Description
Add a `<Trucate />` component.

``` jsx
<Truncate
  ellipsis="..."
  multiline
  resizableByWindow
  text="Lorem Ipsum"
  theme={}
  tooltipPlacement="bottomCenter"
/>
```

### Requirements
- [x] Must render all the text if the size doesn't exceed the parent element size.
- [x] Must truncate the text size exceed the parent element size.

**Comment by Deivis** [comment]
This component could be used in the table to solve the following problem:
![image 1](https://user-images.githubusercontent.com/1773766/46087500-dba81300-c180-11e8-94ad-e018989a8286.png)
In this email case a toolptip to show the full email must also be added.

**Comment by vagnervst** [comment]
Esse problema ocorre também no modal de captura:

![image](https://user-images.githubusercontent.com/18339615/50999064-777f4400-1510-11e9-9299-3a1aca0899f3.png)

E também na página de detalhes da transação:

![image](https://user-images.githubusercontent.com/18339615/50999145-a5fd1f00-1510-11e9-99b0-78728322e47f.png)
