### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by Deivis** [pagarme/former-kit#215]
### Context

Upgrade all dependencies, and fix interfaces problems.

### Example
 
Issue #209  is a good example of a small problem caused by an outdated dependency. 
And the usage of old tools like `webpack` and `babel` keep us tied to a bunch of small problems which could break everything sometimes keeping all updated we also avoid a lot of security threats 
and improve some tools performance like (Storybook)[https://github.com/storybooks/storybook/].

### Description

This issue aims to upgrade all `dependencies` and all `devDependencies` of the project. The upgrade process may create some errors due to the dependencies interfaces, these errors should be solved in the upgrade process.
The major upgrades will be:
`babel` from version 6.26.0 to version 7.2.2
`jest` from version 22.1.4  to version  23.6.0 
`react` from version 16.2.0 to version 16.7.0
`storybook` from version 3.3.11  to version 4.1.7 ( this dependency is splited in 7 parts)
`webpack` from version 3.10.0 to version 4.28
 
### Requirements

- [x] Upgrade all outdated dependencies.
- [x] Refactor new dependencies interfaces usages.

**Comment by Deivis** [comment]
Resolve #209

**Comment by rsmelo** [comment]
publicado na versão https://github.com/pagarme/former-kit/releases/tag/1.0.0
