### ISSUE TITLE
Conflict between react-vanilla-form and react-maskedinput

### ISSUE THREAD

**Issue by uselessdev** [pagarme/former-kit#218]
### Context
Currently we use two libs to handle with forms: `react-vanilla-form` and `react-maskedinput`.

The first one (react-vanilla-form) is to handle forms, one of the characteristics of this lib is add a function in the `onChange` prop.

The second (react-maskedinput) serves to create masks in the input for when a data needs to have a specific format: eg: a zip code `99999-999` added in this way in the input: `mask="11111-111"`

**Problem:**
The problem is that there is a rather strange conflict between the two libs: when we create an input with a mask, for some reason it does not end up calling the onChange added by react-vanilla-form, causing the updates to fail to happen properly.

Thus creates the need to have specific functions for these inputs with masks for example: `handleChangeWithMask` and manually add them to the `onChange` props of each input that needs masks.

After testing with other libs, I realized that using the react-input-mask lib the changes work normally without the need to have a function passed manually by the prop `onChange`.

### Requirements
**Checklist**
- [x] Must update the states correctly without changing the mask format and without changing the components already created with `onChange`.
- [x] Should work correctly after removing the manually added onChange props.

**Comment by rsmelo** [comment]
publicado na versão https://github.com/pagarme/former-kit/releases/tag/1.0.0
