### ISSUE TITLE
Dropdown with searchable input

### ISSUE THREAD

**Issue by geison20** [pagarme/former-kit#220]
### Context
Dado as necessidades de desenvolvimento é importante termos um componente que seja um dropdown e que possua um input para buscar pelo dados.

### Example

![captura de tela de 2019-01-31 13-31-44](https://user-images.githubusercontent.com/14280184/52202991-33553a00-2857-11e9-97b1-1ccc2e1eb316.png)

### Description
Esse componente deverá receber um array de objetos com todos os dados necessários para apresentar ao usuário dando a possibilidade de fazer uma busca dentro do componente.

**Comment by uselessdev** [comment]
🤔  @geison20 talvez esse [pull request](https://github.com/pagarme/pilot/pull/944) resolva
