### ISSUE TITLE
DateInput does not update dates when new props are received

### ISSUE THREAD

**Issue by vagnervst** [pagarme/former-kit#240]
### Context
DateInput uses local state to deal with its dates but has a prop to interfere with it at the same time. Currently it only works correctly when mounting, but not through its lifecycle updates.

### Example
![dateinput error](https://user-images.githubusercontent.com/18339615/54054960-5e220d80-41ca-11e9-9c0d-b371cd5786cc.gif)

### Requirements

**Checklist**
- [x] DateInput update its state from props

**Comment by Deivis** [comment]
Done in #241
