### ISSUE TITLE
Create a component classification list

### ISSUE THREAD

**Issue by Deivis** [pagarme/former-kit#256]
### Context

This issue aims to collect information and classify the component in the following classes:

#### Mobile friendly
The component works in a responsible way and the functionality is equal to the web version.

#### Mobile usable
The component can be used in a mobile page with some adjusts.

#### Mobile unfriendly
The component doesn't work on a mobile page or its usability is very compromised making it impossible to use.

### Example
 
The classification should be made like the following example([here](https://www.tablesgenerator.com/markdown_tables) is a markdown table creator to aux):

| Component | Status | Reason |
|:---------------------:|:------------------:|:-------------------------------------------------------------------------------------------------------------------------------------:|
| Alert | mobile friendly | Works fine in mobile |
| Avatar | mobile friendly |  |
| BulletSteps | mobile friendly | But seems useless in a mobile environment |
| Buttons | mobile friendly | Click action feels laggy. Works better with huge size and could have `tap` events implemented |
| Calendar | mobile unfriendly | Heavy and Laggy interactions with bad usability |
| CalendarInput | mobile unfriendly | Deprecated |
| Cards | mobile friendly | It needs minor adjustments. |
| Checkbox | mobile friendly | It needs minor adjustments. |
| CheckboxGroup | mobile friendly | It needs minor adjustments. |
| DateInput |  mobile unfriendly | This component uses a lot of web-specific implementations which, compromise the mobile usability |
| DateSelector | mobile unfriendly | This component uses a lot of web-specific implementations which compromise the mobile usability |
| DropDown | mobile friendly |  |
| FlexBox | mobile friendly |  |
| Footer | mobile unfriendly | This component has several mini components/images and needs adjustments. |
| Grid | mobile friendly | It needs minor adjustments. |
| Header | mobile unfriendly | This component has several mini components/images and needs adjustments. |
| Image | mobile friendly |  |
| Inputs | mobile friendly |  |
| Landing | mobile unfriendly | Landing is the Login Component with several mini components, it's interesting to make adjustments. The format of today is pretty odd. |
| Layout | mobile unfriendly | Layout is literally the Dashboard template with several components, it's interesting to make adjustments. |
| Legend | mobile friendly |  |
| Modal | mobile unfriendly | It needs width and position adjustments. |
| Pagination | mobile friendly |  |
| Popover | mobile unfriendly | It needs to be adapted/changed to another form of interface. |
| Progress | mobile friendly |  |
| RadioGroup | mobile friendly | It needs minor adjustments. |
| SegmentedSwitch | mobile friendly | It needs minor adjustments. |
| Sidebar | mobile unfriendly | It needs to be adapted/changed to another form of interface. |
| Snackbar | mobile friendly | It needs minor adjustments. Be careful to always put inside a component that involves this, such as Card. |
| SpacedSegmentedSwitch | mobile friendly | It needs minor adjustments. |
| Spacing | mobile friendly |  |
| Steps | mobile friendly |  |
| Switch | mobile friendly | It needs minor adjustments. |
| TabBar | mobile friendly |  |
| Table | mobile friendly | Depending on the content and number of columns, it's mobile friendly. You can't do very extraordinary things. |
| Tags | mobile friendly |  |
| Tooltip | mobile unfriendly | This component is designed for a desktop environment its usability is terrible for mobile environments  |
| Transition | mobile friendly |  |
| Typography | mobile friendly |  |

**Comment by miguelssrs** [comment]
# Component Classification
| Component | Status | Reason |
|:---------------------:|:------------------:|:-------------------------------------------------------------------------------------------------------------------------------------:|
| Alert | mobile friendly | Works fine in mobile |
| Avatar | mobile friendly |  |
| BulletSteps | mobile friendly | But seems useless in a mobile environment |
| Buttons | mobile friendly |  |
| Calendar | mobile unfriendly | Deprecated |
| CalendarInput | mobile unfriendly | Deprecated |
| Cards | mobile friendly | It needs minor adjustments. |
| Checkbox | mobile friendly | It needs minor adjustments. |
| CheckboxGroup | mobile friendly | It needs minor adjustments. |
| DateInput |  mobile unfriendly | This component uses a lot of web specific implementations which, compromise the mobile usability |
| DateSelector | mobile unfriendly | This component uses a lot of web specific implementations which  compromise the mobile usability |
| DropDown | mobile friendly |  |
| FlexBox | mobile friendly |  |
| Footer | mobile unfriendly | This component has several mini components/images and needs adjustments. |
| Grid | mobile friendly | It needs minor adjustments. |
| Header | mobile unfriendly | This component has several mini components/images and needs adjustments. |
| Image | mobile friendly |  |
| Inputs | mobile friendly |  |
| Landing | mobile unfriendly | Landing is the Login Component with several mini components, it's interesting to make adjustments. The format of today is pretty odd. |
| Layout | mobile unfriendly | Layout is literally the Dashboard template with several components, it's interesting to make adjustments. |
| Legend | mobile friendly |  |
| Modal | mobile unfriendly | It needs width and position adjustments. |
| Pagination | mobile friendly |  |
| Popover | mobile unfriendly | It needs to be adapted/changed to another form of interface. |
| Progress | mobile friendly |  |
| RadioGroup | mobile friendly | It needs minor adjustments. |
| SegmentedSwitch | mobile friendly | It needs minor adjustments. |
| Sidebar | mobile unfriendly | It needs to be adapted/changed to another form of interface. |
| Snackbar | mobile friendly | It needs minor adjustments. Be careful to always put inside a component that involves this, such as Card. |
| SpacedSegmentedSwitch | mobile friendly | It needs minor adjustments. |
| Spacing | mobile friendly |  |
| Steps | mobile friendly |  |
| Switch | mobile friendly | It needs minor adjustments. |
| TabBar | mobile friendly |  |
| Table | mobile friendly | Depending on the content and number of columns, it's mobile friendly. You can't do very extraordinary things. |
| Tags | mobile friendly |  |
| Tooltip | mobile friendly |  |
| Transition | mobile friendly |  |
| Typography | mobile unfriendly |  |

**Comment by vagnervst** [comment]
In the table below I added only the components I noticed a difference from what was already reported on this issue, for the others I had the same experience as @Deivis and @miguelssrs:

|       Component       |       Status      |                                                                 Reason                                                                |
|:---------------------:|:-----------------:|:-------------------------------------------------------------------------------------------------------------------------------------:|
|        Buttons        |  mobile friendly  |                                            Click action feels laggy. Works better with `huge` size                                      |
|        Calendar       | mobile unfriendly |                                                       Date selection feels laggy                                                      |
|      DateSelector     | mobile unfriendly |                                                         Didn't render at all                                                          |
|          Grid         | mobile unfriendly |                                                         Didn't render at all                                                          |
|     LinearProgress    |  mobile friendly  |                                                                                                                                       |
|        Progress       |  mobile friendly  |                                                                                                                                       |

**Comment by rsmelo** [comment]
I only added components that i notice something different from the previous reviews

| Component | Status | Reason |
|:---------------------:|:------------------:|:-------------------------------------------------------------------------------------------------------------------------------------:|
| Checkbox | mobile friendly | The animations are a bit slow |
| CheckboxGroup | mobile friendly | The animations are a bit slow |
| DateSelector | mobile unfriendly | Didn't render at all |
| Grid | mobile friendly | Responsive example didn't render |
| Inputs | mobile friendly | a bit laggy when typing |
| Linear Progress | mobile friendly |  |
| Pagination | mobile friendly |  The animations are a bit slow |
| RadioGroup | mobile friendly | The animations are a bit slow  |
| Transition | mobile friendly | The animations are a bit slow |
