### ISSUE TITLE
Steps component

### ISSUE THREAD

**Issue by derekstavis** [pagarme/former-kit#89]
### Exemplo

![screenshot from 2018-04-18 14-10-03](https://user-images.githubusercontent.com/1611639/38947222-4f509d88-4312-11e8-86df-057416c7229a.png)
![screenshot from 2018-04-18 14-09-47](https://user-images.githubusercontent.com/1611639/38947223-4f6ee25c-4312-11e8-9ab5-f1585136f6e1.png)

### Descrição técnica

```jsx
<Steps
  steps={[
    { id: 'identification', title: 'Identificação' },
    { id: 'confirmation', title: 'Confirmação' },
  ]}
  status={[
    { id: 'identification', status: 'success' },
  ]}
/>

// Este componente usa um componente menor chamado `Step`.

steps.map(step =>
    <Step
      key={step.id}
      number={1}
      title={step.title}
      status="success"
    />
))
```

### Requisitos e Critérios de Aceite

- [x] Deve ser incluido no `former-kit`
- [x] Deve renderizar uma lista de passos
- [x] Deve mostrar um ícone de checked quando o passo estiver com estado de sucesso
- [ ] Deve mostrar estado de erro quando tiver erro (cc @pagarme/ux falta estado de erro)

**Comment by alexandralugli** [comment]
O componente step tem como objetivo mostrar o progresso de navegação dentro de uma sequência numérica. É um caminho que ajuda a identificar quantos pontos ainda existem para concluir uma tarefa, para situar e diminuir ansiedade.

Dessa forma, entendemos que ou o passo está concluído ou não está, já que o usuário não está apto a prosseguir para o próximo passo se houver algum erro. Estados de erro e sucesso são resultados informados no conteúdo abaixo deles.

Cenários:
1. Step concluído: ícone √ + texto cinza
2. Step atual: Texto verde
3. Próximo step: Texto cinza
