### ISSUE TITLE
Sugestion: Use class properties on every component 

### ISSUE THREAD

**Issue by vcapretz** [pagarme/former-kit#92]
### Context

If we enable the right babel preset we can start using class properties, so the usual: 
```js
constructor (props) {
  super(props)

  this.handleChange = this.handleChange.bind(this)
  this.state = {
    something: true,
  } 
}

handleChange () {
   ....
} 
```

can be replaced by

```js
state = {
  something: true,
} 

handleChange = () => {
   ....
} 
```

as it is currently not a JavaScript standard some linters can yell at us, to fix that we just need to add
`"parser": "babel-eslint",` to the eslint config file

**Comment by uselessdev** [comment]
Hi @vcapretz, I was a bit confused, what exactly is the problem that would solve it? Or what motivation to do that?

**Comment by vcapretz** [comment]
it's just a suggestion! it allows us to change the sintax to a newer one, but that doesn't impact on anything else (like performance, etc) 

if you feel it's not necessary we can just close this issue ;)
